version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6
     steps:
       - checkout
       - run:
          command: |
            echo "hello world"
            npm install
       - run:
          command: |
            echo "Running tests"
            npm run test:once
